### ISSUE TITLE
Problem with Google 2-Steps Authentication

### ISSUE THREAD

**Issue by andreisusanu** [shumingch/gnome-email-notifications#12]
![sadsa](https://user-images.githubusercontent.com/2534555/32019822-0d6cbb28-b9d7-11e7-8451-e52cabf2d729.png)

**Comment by andreisusanu** [comment]
Never mind. I managed to solve it by connecting using 2-Step Authentication on Gnome Online Accounts.

**Comment by shumingch** [comment]
So you didn't fully log in to Google the first time?

**Comment by andreisusanu** [comment]
I was logged in and the extension worked perfectly at the beginning. After that I have activated the 2-Step Authentication, and logged in to GMail successfully. But the extension stopped working.

To make it work I added my Google account to Gnome's Online Accounts. This solved the problem.
