### ISSUE TITLE
Feature request: support for "IMAP and SMTP" accounts

### ISSUE THREAD

**Issue by guzzard** [shumingch/gnome-email-notifications#14]
Would it be possible to add support for "IMAP and SMTP" accounts?

Great extension, thanks!

**Comment by shumingch** [comment]
It definitely is possible. Might take a while though!

**Comment by Feichtmeier** [comment]
Thad would be indeed cool.

**Comment by shumingch** [comment]
Gnome Shell Extensions have no IMAP/SMTP api and i'm not going to write my own.
