### ISSUE TITLE
Forbidden Error 403

### ISSUE THREAD

**Issue by netije** [shumingch/gnome-email-notifications#16]
Please instead of https://mail.google.com/mail?account_id=myemail@gmail.com&message_id=3123131313&view=conv&extsrc=atom
try to use URL
https://mail.google.com/mail/u/?account_id=myemail@gmail.com&authuser=myemail@gmail.com&message_id=3123131313&view=conv&extsrc=atom&pli=1#

Seems like it will automatically open correct account.

**Comment by shumingch** [comment]
Nice find!
