### ISSUE TITLE
Feature request: change notification icon for GMAIL/outlook/etc

### ISSUE THREAD

**Issue by Feichtmeier** [shumingch/gnome-email-notifications#18]
Hi - thank you for making this extension!

It's basically the only way to use gnome online accounts for gmail outside of evolution! And it works!

My request:

Provide an equivalent icon for each mail provider you support
-> new gmail -> use gmail icon in the gnome notification
-> new outlook mail -> use outlook icon in the gnome notification

Best regards, Frederik

**Comment by shumingch** [comment]
Thanks for the feedback!
I chose the current icon because it automatically matches your current gnome theme. Having icons would look a bit out of place.
