### ISSUE TITLE
Error after update 

### ISSUE THREAD

**Issue by zoecastro** [shumingch/gnome-email-notifications#29]
![image](https://user-images.githubusercontent.com/49070447/102822303-c5608000-43a6-11eb-8c53-22bbdd90224b.png)

**Comment by Lzrnk** [comment]
Same problem, error after update

**Comment by shumingch** [comment]
You probably got this error: "A different version was loaded previously. You need to log out for changes to take effect."

I know, it's annoying that it doesn't tell you the actual error message.

**Comment by Lzrnk** [comment]
Thank you. Now it works.
