### ISSUE TITLE
Nothing happens when i click on the notification

### ISSUE THREAD

**Issue by flobb** [shumingch/gnome-email-notifications#30]
Ubuntu 20.04 with Gnome 3.36.8 (vanilla) on X11.
I'm using Gnome Online account on my Gmail account.
Chromium (the snap version) is the default application for website and mail.

When i have a new mail on Gmail, a notification appear.
When i click on the notification, the notification disappears and nothing happens.

Expected behavior : When i click on the notification, Chromium open the Gmail website on the right mail.
But I'm not sure the extension handles this?

**Comment by bnuccio** [comment]
This really doesn't work right. What you are seeing most likely is the default gnome pop up. 

I noticed at least in my case gnome deletes the folder ~/.local/share/gnome-shell/extensions/GmailMessageTray@shuming0207.gmail.com on reboot, or randomly. journalctl will show all kinds of errors before deletion. 

If you want to play around with it, 1st thing. Run this -

gnome extensions list

If you don't see the extension, its not installed. 

Make sure you have the requirements. Download the zip file and run -

gnome extensions install GmailMessageTrayshuming0207.gmail.com.v20.shell-extension.zip

Reboot

Now run gnome extensions list. You should see it. And works as expected until gnome randomly removes it, or a reboot happens. I pretty much gave up messing around with it and using a browser extension instead for gmail notifications.
