### ISSUE TITLE
'Status 0: null' notification

### ISSUE THREAD

**Issue by finalcoz** [shumingch/gnome-email-notifications#46]
Thank you for the update, which allows me to use this extension with Gnome 43 (Fedora 37) - I was missing it. Everything seems to work well (no errors I saw previously in logs so far), except that often I get a 'Status 0: null' notification. It doesn't seem to break anything, so not a major problem. I am using Google in Gnome Online Accounts. In the journal I see this many times:
`gnome-shell[2281]: [Gnome Email Notifications] Status 0: null,scanInbox/</<@/home/UserName/.local/share/gnome-shell/extensions/GmailMessageTray@shuming0207.gmail.com/InboxScanner.js:73:33`

**Comment by dteskera** [comment]
i just changed that line locally in InboxScanner.js to this: 
`} else if (msg.get_status() !== 2 && msg.get_status() !== 3 && msg.get_status() === 0) {`
and it seems to work as expected.

**Comment by Gragt** [comment]
> i just changed that line locally in InboxScanner.js to this: `} else if (msg.get_status() !== 2 && msg.get_status() !== 3 && msg.get_status() === 0) {` and it seems to work as expected.

That hasn’t apparently made any noticeable difference for me—I do appreciate your input, though!

From what I can tell, that notification mostly takes care of itself and goes away on its own soon enough—at the next mail check? Nothing breaking, and I appreciate that it doesn’t create a pop-up, but I wish there were a way to suppress those.

**Comment by dteskera** [comment]
> msg.get_status() === 0 should be msg.get_status() !== 0

you're right. in my code it is !== 
i was replying to this issue from memory :smile:

**Comment by Gragt** [comment]
By the way, I had the notification appear again after the latest update. It is far less spammy than before but it is still there—`journalctl /usr/bin/gnome-shell | grep 'Status 0'` shows that  it happened to a maximum of 5 times a day or not at all in the last week.

**Comment by Gchladek** [comment]
The Status 0 is a generic status code indicating that an error occurred while sending the request or receiving the response. The #50 fix addresses the issue of the request frequently timing out due to the default timeout being too short. However, you may still receive Status 0 notifications for various other unrelated reasons, such as the server being unreachable.
